### PR TITLE
Setup git for private github repositories

### PR DESCRIPTION
**Pull request by Arkoprabho**

### CODE REVIEW

**Comment by Arkoprabho** [comment]
I am not sure how this will behave in case the GITHUB_PASSWORD is not provided.
Do you think we should work to make that as a variable for action along with making it optional?

**Review by vitulrana — APPROVED** [review]

**Comment by vitulrana** [comment]
> I am not sure how this will behave in case the GITHUB_PASSWORD is not provided.
> 
> Do you think we should work to make that as a variable for action along with making it optional?

I don't think we are explicitly providing AWS creds to action, so this should also work

**Comment by vitulrana** [comment]
> > I am not sure how this will behave in case the GITHUB_PASSWORD is not provided.
> > 
> > Do you think we should work to make that as a variable for action along with making it optional?
> 
> I don't think we are explicitly providing AWS creds to action, so this should also work

Just checked in PMS Infra we provide GITHUB_TOKEN in the action, we should just use same variable maybe?

**Comment by Arkoprabho** [comment]
Yeah. The token and password have differing privileges. The token allows the action to interact with the current context of the PR, while the oauth password is a PAT for fetching remote modules.
We cannot grant extra privileges to the token, but I am sure we can modify it for the PAT. Let me check it out

**Review by bhatiaparas177 — APPROVED** [review]
lgtm

**Review by vitulrana — APPROVED** [review]

**Pull request merged**
